FROM mcr.microsoft.com/dotnet/sdk:6.0-jammy AS build
WORKDIR /app

# Copy everything else and build
COPY ["API", "API"]
COPY ["Domain", "Domain"]
COPY ["Infrastructure", "Infrastructure"]
RUN dotnet publish "API/API.csproj" -c Release -o /app/out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0-jammy
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "API.dll"]
