FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine

WORKDIR /app

COPY ./app/out /app/

# create a new user and change directory ownership
RUN adduser --disabled-password \
  --home /app \
  --gecos '' dotnetuser && chown -R dotnetuser /app

# impersonate into the new user
USER dotnetuser

EXPOSE 8080

ENTRYPOINT ["dotnet", "API.dll"]
